sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
  - secure: D490u3uoAtQkY6EAlRUfyMezDvrY8zu5CQinAfYzS36jJiEfHhnPsq7BA/VVN97vAB1wPK2+1bqYOz9M3AfdObbBihsI3X2yzoid1uoogNhWrky8SEjooORx5Y2NwMMmhol7gtXo44AILSBGpZjCbiug27S2/itXt6YeOKZe3wuYSMTMAim9+xFh/HB0aASZJJv85VRqSUxMqCmrGzDRLcODwH/3cFunsQ9GyZTJn2zMDX8zMCVndm++ZlVkwbpb0cXMKKM5tu6xSDi8CNJ841oDJuYmh67lqjDyoFBRXRwnj2tFYJXDKMeNM5uwXsTP6vg6B3He9xyyJIfcKHHPCrEzM1vLvKuU874sTP2NPfDiYykYYxCpLQNHPspTKo2IgpX/M2zxK3twVXkPHrHpV22cwpMI3TkKwnnUAvNRZejcTTQ3CvRi7v02F3iDladz2pbw6Hvo/fszssZGlNHtk2eSX6jE2U3C0FPCpZ5R93MFoL3B2WBEwKbwqT7s7Od9moJUBwXd9MTmukzmYBzG3b61tku5N18iykNlP6cLN4W2CamR7v5cV7VpGAUXW9UUoMoUTnMFHW9ERMZjrN/EkSul/l0A/V+BYX1cVOCzrHOxCOA1UxgI2HsfFIKYXx6wbV6s995jc9kZ/xt0wJs2WahxKschSthXpUKETP0VZ+8=
  - secure: AP74QmE3UIGD5cCSqn87xncOe/dltAkZ+S2xUjkatr6WSVUVnngqcsAeZYqwWwcNe91mRSFeSnRqksitULJerKu5VQhDb7sPpYE1sMPNVjkAI+6ihIcU0eCWFCJSl6ZWmf6vohIzHyVLSeckz9Ezpc/82+L0R9aqN4N3yVF+nPBGGDa8cQqw/xmJ0wiZtOy6e9Yr9cjw1kssemGjpVOct+BlbvxaZIQuUZMs7nEbGRZeMEBkEKPJoJx3riD7R7esO9tl9jm/bXVUEdd/fpUjURTyjgpXPLQr3T9+KE5WWtbGBbl1jJ24UGb0+SytKt0svY+iGR4FWleWzuYQVLGONSwPdKVWZibVzVV+YJBNtzDTBRbB8FBiCa2t0x3/rvNsIB2HVJ8ksbKj0hnkeooch+UNNN8hRWs5c2RzCKuShkbkIDnNf+GNr3/bp70K9+/3PFmse9gDgleGM33rTqxKL80lWtC6khV981CdClGcn8pP6v+KjM3gqHe9opqmh5lkvF27nWloa8t16A+8rHdzFXtzS/BamH86Id7wYACkoL/5376EBgSAPMFI+r9xkprNVS1GWa6/d+CoB0fGKYL6fr5lhEEoytNaB/oUIRTRRupb7qzM62MsUhy9WjU3kSR+FMAppWsmpWaQABgmmCNV+ZZtNlC8bBA9eBfz950Uc9A=
  before_install:
  - openssl aes-256-cbc -k "$password" -in id_rsa.enc -out deploy_key -d
after_success:
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
